travis:
  secure:
    BINSTAR_TOKEN: kO0Ap35gt2FhFTL5IsYxmI+aXfeMci05RUui7V/u/LTU5t3DsYmYqH7kDHoLHc88tZZiiN0NfYAuYohgyH2XEeoYL2l6dy6rcrnWF2OPSfW7JNCHhsjGJ6SG9oHXn+WYy9AnuezeHhqn8s9heR2dcg+cdgpnrzMsq+PN/dtisPgeAxTHWJHXvHexpzL5Ma2CgEeA1YxItHY9rEh0czpzfD70updDCW4VqrysKHaPKMfSRTgYmK3SGmaXQ/8p/MPGmP2GAN98CPvBDnwXVQMdPWR7J6AIqFxDUjDSinRQqUJRinGUsRjsZiCW9ujUg4eGD/rgY4cZKKeCv+XyPgzJsPoF+oyn1AfznmA9rpZoAUFoa2ME7DYd/mdw4gxGx+cHhcLpWorVvwKDNCmchyiCiCL1Qrpfu9nDc7Ivx7f/j5A13AFObQEWKUWK1gKqpav3muG5Nw4GCfE/qpdFGuoUPvMlHlVELh+dw2O47LdRDAir4pUbav3cXOoaqbWyr+16KXKufCziYkidEk9DbwuOgOIl5GhA0xlMD80Sdy42xPrPpibNxW2lyd0ukngXi63PyZidNNz/piiu37eQKkUhnVmovnqztRh4yf6HU3jSAne7XwVi+Pe+6hqJkg4H3SiUnxz/Nzjjk1u4f48/cPySSvzTb5Fp2KNaYQVQ6eNZyTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
