travis:
  secure:
    BINSTAR_TOKEN: Ntw2Q0QpekxkrZKVkl2f9BHbxd5b/R9itgLsLoNifRUiRUSmcrLcynRHoSnsUD4Wq65ARrLxDY5dj+Ip7AGhVBgaYFlBdsXH6ywJfTH/I3vuhCT2o/AOMmSDoqDtZQUntGkmcwqe+1b1xhH1wsKXIkIwLxaKsfC2oKaPYlIwmfSrkDDgST3PaSAKnn1FWBvC/lyi9xVPpfDg8pKpa0qKVrR4/Bc/V9D5XKQ5YgjEIzxuH9fHfeCcnepZ4Liui9hpKKmqUP0enlAIOPPmVatybt3WAQP/3azKCAa11FiGtG7izdknYbqSmUCnJ+CECuZYfnRbVZPR7Yt3GeF9YlX27Mi9kOWgz0sVSxTZ15YmdglNi+GwvnAhOE6Wp5ivK90iKLaNqoxaIrE2jMyNfTugRfBGpqXZ7y9xFHMt49EGn/qY3w8rMVBMLOJg+wxEsNDh9zeJrkqtygVuc0OcsettHo7Yg8ildxquwzTiYUqHDQZU0VdX/FsKFSddSnKf6X6R7jAW1lCJB4E46vewMK7CT5DaFE3/KN/Nyb6rtrhXx67aR494dHa1dqB00H5lgMUcBY0SrT7ZYzGPW8szU+matRBrPFD4QzL+FjhuZvmS6decgIHs4UmZImCQE7KpE0aIIefFWXlsd0OTvvT7GM7C82y/ocp0NObNydwsPaGhUyg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
