travis:
  secure:
    BINSTAR_TOKEN: NxCNBUhfuA0zqCHBxBPS+3IVG49j4n2yQ5CFfbcrsczv43DA/Vsxy/d4HtdB7nTFIYXBGV4zvxWSKQZy8FNtouLx3xhEITI3+z4/9OzSaCY/zEPUjkWbIPcmSBeMdf4CSqFpI1Ne1cVvKE9evJ4+uBo9bfcZ60zraS1xNqHk5fJcXMrz/d+tL2N8zTckJFZ2qlsEZPM/RUzeUqwlslGwq+IKjpX7zts0lNEeQHGRwzOtkGLlEzWCj5ihYfG2TUaDiTlrlJ3E/YGdtZqIrmOCjUnmgrIBkhhqyVnAIPmGgfSbwjDttiMptjlp+VWnB0TBVWV8QFvdto9O72gnICJ+tjPFWAOdT81i5gY5Hs+tL6T6cWf3BiuNOMO2dxH6qH58ImBibDwpCkWKoP5Xzef9jZJINPuuCaQS+QzVWx1AvQkZ+NeBwbMi0fRAYK3KCCtA0yYj3JEkEsFd7SoGnmd7iFdi8qgi0q+VexClRz5ROG1yoM1EiHw3Ft+mrjKmtmDGn2VmpUGFbdTMMlBHM8GhbgGM081xrse7ZWt683wg+iIA8nPsevvTvv9BUpFI4VFaR6UnOMI02KwAnI1QzDubRrBiq1jwHfd5xh7/B7+DH9+uNJvAU93XY3aQ5A8OL4DIjJeidKR7z9FgmHSETVW+ivxFdw1Y9lvtnuqxpcgTjBo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
